apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: aimmopost-image
  newName: aimmopostregistry.azurecr.io/aimmopost
  newTag: v1
- name: aimmopostregistry.azurecr.io/aimmopost
  newTag: 41d54a185b6a0cd0d966f085eb33abeeca5c010a
